const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const includeDirs = [".github", "adapters", "bin", "docs", "evals", "scripts", "skill"];
const includeFiles = ["README.md", "CONTRIBUTING.md", "SECURITY.md", "package.json"];
const bannedPatterns = [
  { pattern: word("can" + "non"), reason: "informal metaphor" },
  { pattern: word("canh[aã]o"), reason: "informal metaphor" },
  { pattern: word("form" + "iga"), reason: "informal metaphor" },
  { pattern: word("por" + "ra"), reason: "unprofessional language" },
  { pattern: word("w" + "tf"), reason: "unprofessional language" },
  { pattern: phrase("generated by " + "chatgpt"), reason: "generated-content marker" },
  { pattern: phrase("as an " + "ai"), reason: "generated-content marker" },
  { pattern: phrase("ai " + "slop"), reason: "informal AI phrasing" },
  { pattern: phrase("architecture " + "theater"), reason: "informal phrasing" },
  { pattern: /dump(ing)? a full prompt/i, reason: "informal phrasing" }
];

const failures = [];

for (const file of includeFiles) {
  scanFile(path.join(root, file));
}

for (const dir of includeDirs) {
  walk(path.join(root, dir));
}

if (fs.readdirSync(root).some((entry) => entry.endsWith(".tgz"))) {
  failures.push("Generated .tgz package found in project root. Keep tarballs out of source control.");
}

if (failures.length) {
  console.error("Public hygiene check failed:\n");
  for (const failure of failures) {
    console.error(`- ${failure}`);
  }
  process.exit(1);
}

console.log("Public hygiene check passed.");

function walk(dirPath) {
  if (!fs.existsSync(dirPath)) return;

  for (const entry of fs.readdirSync(dirPath, { withFileTypes: true })) {
    const entryPath = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      walk(entryPath);
    } else {
      scanFile(entryPath);
    }
  }
}

function scanFile(filePath) {
  if (!fs.existsSync(filePath)) return;
  if (!/\.(js|json|md|mdc|yaml|yml)$/.test(filePath)) return;

  const relativePath = path.relative(root, filePath);
  if (relativePath === path.join("scripts", "public-check.js")) return;

  const text = fs.readFileSync(filePath, "utf8");

  for (const { pattern, reason } of bannedPatterns) {
    if (pattern.test(text)) {
      failures.push(`${relativePath}: ${reason} (${pattern})`);
    }
  }
}

function word(source) {
  return new RegExp(`\\b${source}\\b`, "i");
}

function phrase(source) {
  return new RegExp(source, "i");
}
